// Generates fixtures/sample-aic-jwt.json using the AIC-JWT TypeScript
// reference implementation (../ts/aicjwt.ts).  The fixture is then
// verified by third-party libraries in verify-jose.mjs and
// verify-jsonwebtoken.mjs.
import { mkdir, writeFile } from "node:fs/promises";
import {
  MODE_AUTHORIZED,
  TYP_DA,
  TYP_OUTER,
  b64uEncode,
  keyHashOf,
  signCompact,
} from "../ts/aicjwt.ts";

const subtle = globalThis.crypto.subtle;

async function genKey() {
  return subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, ["sign", "verify"]);
}

const principal = await genKey();
const agent = await genKey();
const issuer = await genKey();
const nowSec = Math.floor(Date.now() / 1000);
const lifetime = 3600;
const nonceBytes = new Uint8Array(32);
globalThis.crypto.getRandomValues(nonceBytes);
const nonce = b64uEncode(nonceBytes);
const principalId = "corp.com:zhangsan";
const agentId = "agent:db-analyst-01";
const asUrl = "https://as.example.com";
const rsUrl = "https://rs.example.com";

const principalBinding = {
  realm: "corp.com",
  id: "zhangsan",
  key_hash: await keyHashOf(principal.publicKey, "sha-256"),
  hash_alg: "sha-256",
};

const capabilities = [{ scheme: "database", id: "query:SELECT", params: { max_rows: 100 } }];

const daClaims = {
  ver: 2,
  iss: principalId,
  sub: agentId,
  aud: [asUrl],
  exp: nowSec + lifetime,
  iat: nowSec,
  jti: nonce,
  agent_id: agentId,
  principal: principalBinding,
  reason: { code: "DATA_ANALYSIS", desc: "scheduled analysis" },
  capabilities,
  delegation_mode: MODE_AUTHORIZED,
  requested_lifetime: lifetime,
  ts: nowSec,
  nonce,
};

const daToken = await signCompact(
  { alg: "ES256", typ: TYP_DA, kid: "principal-1" },
  daClaims,
  principal.privateKey,
);

const outerClaims = {
  iss: asUrl,
  sub: agentId,
  aud: [rsUrl],
  iat: nowSec,
  exp: nowSec + lifetime,
  jti: nonce,
  cnf: { jkt: await keyHashOf(agent.publicKey, "jkt") },
  aic: {
    ver: 1,
    principal: principalBinding,
    delegation_mode: MODE_AUTHORIZED,
    capabilities,
  },
  da: daToken,
};

const token = await signCompact(
  { alg: "ES256", typ: TYP_OUTER, kid: "issuer-1" },
  outerClaims,
  issuer.privateKey,
);

const issuerJwk = await subtle.exportKey("jwk", issuer.publicKey);
await mkdir("fixtures", { recursive: true });
await writeFile(
  "fixtures/sample-aic-jwt.json",
  JSON.stringify(
    {
      token,
      issuerJwk,
      expected: { iss: asUrl, aud: [rsUrl], sub: agentId },
      note: "ES256 P-256; DA ver=2; authorized mode; generated by AIC-JWT TS reference implementation",
    },
    null,
    2,
  ),
);
console.log("fixture written: fixtures/sample-aic-jwt.json");
console.log("token length:", token.length);
